name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 2.0.0-beta
publish_to: none
homepage: https://github.com/albert-heijn-technology
repository: https://github.com/albert-heijn-technology/platform_maps_flutter/tree/master/packages/platform_maps_flutter
issue_tracker: https://github.com/albert-heijn-technology/platform_maps_flutter/issues

environment:
  flutter: '>=2.11.0'
  sdk: '>=2.17.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: platform_maps_flutter_google_android
      web:
        default_package: platform_maps_flutter_google_web
      ios:
        default_package: platform_maps_flutter_apple

dependencies:
  flutter:
    sdk: flutter

  platform_maps_flutter_apple:
    git:
      url: https://github.com/orihpt/platform_maps_flutter.git
      ref: master
      path: packages/platform_maps_flutter_apple
  platform_maps_flutter_google_android:
    git:
      url: https://github.com/orihpt/platform_maps_flutter.git
      ref: master
      path: packages/platform_maps_flutter_google_android
  platform_maps_flutter_google_web:
    git:
      url: https://github.com/orihpt/platform_maps_flutter.git
      ref: master
      path: packages/platform_maps_flutter_google_web
  platform_maps_flutter_platform_interface:
    git:
      url: https://github.com/orihpt/platform_maps_flutter.git
      ref: master
      path: packages/platform_maps_flutter_platform_interface

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
